import { Appearance, LotType } from "../types";

export const defaultLotData: LotType = {
  _id: "",
  zone: "",
  token: "",
  cover: "",
  siteCode: "",
  url: "",
  address: "",
  hourlyRate: 0,
  payTime: 0,
  fine: 0,
  percentage: 0,
  payingApp: "",
  owners: [],
};

export const appearance: Appearance = {
  theme: "stripe",
  variables: {
    colorPrimary: "#2687e8",
    colorBackground: "#FFFAF9",
    colorText: "#091C62",
  },
};

export const states = [
  { value: "Alabama", name: "Alabama" },
  { value: "Alaska", name: "Alaska" },
  { value: "Arizona", name: "Arizona" },
  { value: "Arkansas", name: "Arkansas" },
  { value: "California", name: "California" },
  { value: "Colorado", name: "Colorado" },
  { value: "Connecticut", name: "Connecticut" },
  { value: "District of Columbia", name: "District of Columbia" },
  { value: "Delaware", name: "Delaware" },
  { value: "Florida", name: "Florida" },
  { value: "Georgia", name: "Georgia" },
  { value: "Hawaii", name: "Hawaii" },
  { value: "Idaho", name: "Idaho" },
  { value: "Illinois", name: "Illinois" },
  { value: "Indiana", name: "Indiana" },
  { value: "Iowa", name: "Iowa" },
  { value: "Kansas", name: "Kansas" },
  { value: "Kentucky", name: "Kentucky" },
  { value: "Louisiana", name: "Louisiana" },
  { value: "Maine", name: "Maine" },
  { value: "Maryland", name: "Maryland" },
  { value: "Massachusetts", name: "Massachusetts" },
  { value: "Michigan", name: "Michigan" },
  { value: "Minnesota", name: "Minnesota" },
  { value: "Mississippi", name: "Mississippi" },
  { value: "Missouri", name: "Missouri" },
  { value: "Montana", name: "Montana" },
  { value: "Nebraska", name: "Nebraska" },
  { value: "Nevada", name: "Nevada" },
  { value: "New Hampshire", name: "New Hampshire" },
  { value: "New Jersey", name: "New Jersey" },
  { value: "New Mexico", name: "New Mexico" },
  { value: "New York", name: "New York" },
  { value: "North", name: "North" },
  { value: "North", name: "North" },
  { value: "Ohio", name: "Ohio" },
  { value: "Oklahoma", name: "Oklahoma" },
  { value: "Oregon", name: "Oregon" },
  { value: "Pennsylvania", name: "Pennsylvania" },
  { value: "Rhode Island", name: "Rhode Island" },
  { value: "South Carolina", name: "South Carolina" },
  { value: "South Dakota", name: "South Dakota" },
  { value: "Tennessee", name: "Tennessee" },
  { value: "Texas", name: "Texas" },
  { value: "Utah", name: "Utah" },
  { value: "Vermont", name: "Vermont" },
  { value: "Virginia", name: "Virginia" },
  { value: "Washington", name: "Washington" },
  { value: "West Virginia", name: "West Virginia" },
  { value: "Wisconsin", name: "Wisconsin" },
  { value: "Wyoming", name: "Wyoming" },
];

export const navbarItems = [
  { value: "/home", name: "Home" },
  { value: "/about", name: "About" },
  { value: "/contact", name: "Contact" },
];
